@cattail = Bog.find_or_create_by!(name: "Cattail waters", ph: 4.7, radioactive: false)
@log = Bog.find_or_create_by!(name: "The log lodge", ph: 5.7, radioactive: false)
@moss = Bog.find_or_create_by!(name: "Mossy Oaks", ph: 5.0, radioactive: false)
@glow = Bog.find_or_create_by!(name: "Glowing Peats", ph: 1.9, radioactive: true)
@neon = Bog.find_or_create_by!(name: "Neon waters", ph: 2.8, radioactive: true)
@boggy = Bog.find_or_create_by!(name: "Boggywood", ph: 4.8, radioactive: false)

@zack = @boggy.frogs.create!(name: "Zack Effrog", age: 30, singing: true)
@jr = @boggy.frogs.create!(name: "Ribbit Downey Jr", age: 50, singing: false)
@demi = @boggy.frogs.create!(name: "Demi Lovatoad", age: 30, singing: true)
@danny = @boggy.frogs.create!(name: "Danny Devitoad", age: 30, singing: false)
