@cattail = Bog.find_or_create_by!(name: "Cattail waters", ph: 4.7, radioactive: false)
@log = Bog.find_or_create_by!(name: "The log lodge", ph: 5.7, radioactive: false)
@moss = Bog.find_or_create_by!(name: "Mossy Oaks", ph: 5.0, radioactive: false)
@glow = Bog.find_or_create_by!(name: "Glowing Peats", ph: 1.9, radioactive: true)
@neon = Bog.find_or_create_by!(name: "Neon waters", ph: 2.8, radioactive: true)
@boggy = Bog.find_or_create_by!(name: "Boggywood", ph: 4.8, radioactive: false)

@zack = @boggy.frogs.find_or_create_by!(name: "Zack Effrog", age: 25, singing: true)
@jr = @boggy.frogs.find_or_create_by!(name: "Ribbit Downey Jr", age: 50, singing: false)
@demi = @boggy.frogs.find_or_create_by!(name: "Demi Lovatoad", age: 30, singing: true)
@danny = @boggy.frogs.find_or_create_by!(name: "Danny Devitoad", age: 65, singing: false)
@hanna = @boggy.frogs.find_or_create_by!(name: "Hannah Montadpole", age: 30, singing: true)

@spider = @glow.frogs.find_or_create_by!(name: "Spider Frog", age: 30, singing: false)
@super = @glow.frogs.find_or_create_by!(name: "Super Toad", age: 35, singing: false)
@captain = @glow.frogs.find_or_create_by!(name: "Captain Amphibian", age: 150, singing: true)
